name: nuget publish

on:
  push:
    branches: [release]

jobs:
  github-publish:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      # Checkout the repo
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      # Setup .NET Core SDK
      - name: Setup .NET core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0'
          source-url: https://nuget.pkg.github.com/nanikit/index.json
        env:
          # Setup the .NET Core SDK with the appropriate auth token to access the GitHub Package Registry
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Run dotnet build and package
      - name: Package
        run: |
          dotnet restore
          dotnet pack --configuration Release
      # Publish the package to GitHub Package Registry
      - name: Publish to github packages
        run: dotnet nuget push Nanikit.Ehnd\bin\x86\Release\*.nupkg
