name: nuget publish

on:
  push:
    branches: [release]

jobs:
  github-publish:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      # Setup .NET Core SDK
      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0'
      # Run dotnet build and package
      - name: Package
        run: |
          dotnet restore
          dotnet pack --configuration Release
      # Publish the package to GitHub Package Registry
      - name: Publish
        run: dotnet nuget push Nanikit.Ehnd\bin\x86\Release\*.nupkg --api-key ${{ secrets.NUGET_API_KEY }}
